apiVersion: v1
kind: Service
metadata:
  name: cortex-api-svc
  namespace: cortex-system
spec:
  selector:
    app: cortex-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
